### ISSUE TITLE
Github Action：根据push tag自动发布release

### ISSUE THREAD

**Issue by Achuan-2** [Achuan-2/Achuan-2.github.io#18]
```yaml
name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: false

```
